apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: aws-acc-10
  description: Personal sandbox AWS account
  annotations:
    aws.amazon.com/account-id: "123456789012"
spec:
  type: aws-account
  lifecycle: experimental
  owner: user1
  subcomponentOf: component:dv-project-10
