apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: dv-project-10
  description: Playground project for Dev & Ops experiments
spec:
  type: service
  lifecycle: experimental
  owner: user1
