apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-template
  title: Simple Template
  description: A simple template that prints a message
spec:
  owner: backstage/techdocs-core
  type: service
  parameters:
    - title: Message
      required:
        - message
      properties:
        message:
          title: Message
          type: string
          description: The message to print
  steps:
    - id: print-message
      name: Print Message
      action: debug:log
      properties:
        message: ${{ parameters.message }}
