apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
  title: Create Official Python Application
  tags: ['official']
spec:
  owner: user1
  type: service
  parameters:
    properties:
      name:
        type: string
        default: world
  steps:
    - id: log
      name: Log
      action: debug:log
      input:
        message: "Hello, ${{ parameters.name }}!"
