name: Print Hi

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      custom_message:
        description: Message to print
        default: hi
        required: false
        
jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Say something
        run: echo "${{ github.event.inputs.custom_message || 'hi' }}"
