name: Print Bye

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      custom_message:
        description: Message to print
        default: bye
        required: false
        
jobs:
  say-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Say something
        run: echo "${{ github.event.inputs.custom_message || 'bye' }}"
